"""
Fixture proof: deterministic test that the full relation discovery pipeline
can produce tradeable EQUIVALENT relations when cross-platform markets exist.

This test:
1. Inserts two cross-platform markets (Polymarket + Kalshi) into the DB.
2. Inserts compiled propositions with matching canonical semantics.
3. Inserts an identity link marking them as VERIFIED.
4. Runs RelationAnalysisService with a mocked SemanticRelationAnalyzer
   that confirms EQUIVALENT as tradeable.
5. Asserts:
   - Typed hypothesis (EQUIVALENT) was generated by RelationHypothesisGenerator.
   - A LogicalRelation with tradeable_relation=True is persisted.
   - relation_type is EQUIVALENT (not same_event_family).
   - The funnel report shows hypothesis_proposals > 0 and hypothesis type EQUIVALENT.

This fixture does NOT require a live LLM or live trading.
"""
from __future__ import annotations

import uuid
from datetime import datetime, timezone
from unittest.mock import AsyncMock, MagicMock, patch

import pytest

from parallax.db.models import (
    CompiledContract,
    CompiledProposition,
    LogicalRelation,
    RawMarket,
)
from parallax.detection.schemas import RelationClassification
from parallax.detection.semantic import SemanticRelationAnalyzer
from parallax.graph.postgres_repository import PostgresGraphRepository
from parallax.prover.service import RelationAnalysisService
from parallax.shared.schemas import RelationType

pytestmark = pytest.mark.anyio

_DL = "2025-12-31T00:00:00+00:00"
_NOW = datetime(2025, 12, 1, tzinfo=timezone.utc)


def _raw_market(session, platform: str, mid: str, group_id: str | None = None) -> RawMarket:
    m = RawMarket(
        id=f"{platform}:{mid}",
        platform=platform,
        market_id=mid,
        title=f"{platform} {mid} — Candidate X wins election",
        description="Will Candidate X win the 2025 election?",
        resolution_criteria="Resolves YES if Candidate X wins.",
        outcomes=["Yes", "No"],
        outcome_prices=[0.55, 0.45],
        category="politics",
        group_id=group_id,
        deadline=datetime(2025, 12, 31, tzinfo=timezone.utc),
        is_closed=False,
        resolution_source="official_source",
        raw_payload={},
    )
    session.add(m)
    return m


def _compiled_contract(session, market_id: str) -> CompiledContract:
    contract_data = {
        "yes_conditions": ["Candidate X wins the 2025 general election"],
        "no_conditions": ["Candidate X does not win"],
        "exclusions": [],
        "ambiguity_terms": [],
        "counterexamples": [],
        "compiler_confidence": 0.92,
        "canonical_subject": "candidate_x",
        "canonical_predicate": "wins_election",
        "canonical_object": "election_2025",
        "temporal_deadline": _DL,
        "oracle_focus": "official",
        "proposition_family": f"election:{market_id.split(':')[0]}:wins",
    }
    row = CompiledContract(
        id=uuid.uuid4(),
        raw_market_id=market_id,
        contract_json=contract_data,
        compiler_confidence=0.92,
        compiler_version="test-v1",
        compiled_at=_NOW,
    )
    session.add(row)
    return row


def _compiled_proposition(session, market_id: str, platform: str) -> CompiledProposition:
    prop_data = {
        "raw_market_id": market_id,
        "canonical_subject": "candidate_x",
        "canonical_predicate": "wins_election",
        "canonical_object": "election_2025",
        "temporal_deadline": _DL,
        "oracle_focus": "official",
        "oracle_scope": "official",
        "proposition_family": f"election:{platform}:wins",  # platform-specific family
        "partition_hint": False,
        "polarity": "positive",
        "semantic_tags": [],
        "compiler_confidence": 0.92,
    }
    row = CompiledProposition(
        id=uuid.uuid4(),
        raw_market_id=market_id,
        proposition_json=prop_data,
        compiler_version="test-v1",
        compiled_at=_NOW,
    )
    session.add(row)
    return row


def _confirmed_classification() -> RelationClassification:
    """Mock semantic return: confirms EQUIVALENT as tradeable."""
    return RelationClassification(
        relation_type=RelationType.EQUIVALENT,
        confidence=0.88,
        reasoning="cross-platform markets describe identical event with same oracle",
        comparison_axes=["yes_conditions", "oracle", "deadline"],
        breaking_scenarios=[],
        is_confirmed=True,
        tradeable_relation=True,
        proof_status="verified",
    )


def _make_analyzer() -> SemanticRelationAnalyzer:
    analyzer = MagicMock(spec=SemanticRelationAnalyzer)
    analyzer.classify = AsyncMock(return_value=_confirmed_classification())
    return analyzer


@pytest.mark.anyio
async def test_fixture_cross_platform_equivalent_produces_tradeable_relation(test_session):
    """
    Full pipeline fixture: cross-platform equivalent markets → tradeable LogicalRelation.
    """
    session = test_session

    # 1. Insert markets
    pm = _raw_market(session, "polymarket", "elec2025-pm")
    ks = _raw_market(session, "kalshi", "ELEC2025-ks")
    session.flush()

    # 2. Insert compiled contracts and propositions
    _compiled_contract(session, pm.id)
    _compiled_contract(session, ks.id)
    _compiled_proposition(session, pm.id, "polymarket")
    _compiled_proposition(session, ks.id, "kalshi")
    session.flush()

    # 3. Stub identity provenance as VERIFIED for the pair
    identity_prov = {
        "canonical_event_id": "event-elec-2025",
        "identity_status": "verified",
        "identity_confidence": 0.95,
        "identity_version": "identity-v3-runtime",
        "links": {},
    }
    with patch("parallax.prover.service.load_identity_provenance", return_value=identity_prov), \
         patch("parallax.prover.service.load_identity_status") as mock_status, \
         patch("parallax.prover.service.load_identity_confidence", return_value=0.95), \
         patch("parallax.prover.service.load_identity_version", return_value="identity-v3-runtime"), \
         patch("parallax.prover.service.load_identity_blocking_reason", return_value=None):

        from parallax.shared.schemas import IdentityResolutionStatus
        mock_status.return_value = IdentityResolutionStatus.VERIFIED

        analyzer = _make_analyzer()
        graph_repo = PostgresGraphRepository(session)
        service = RelationAnalysisService(session, graph_repo, semantic_analyzer=analyzer)

        count = await service.run([pm, ks])

    session.flush()

    # 4. Assert at least one relation was persisted
    assert count > 0, f"Expected > 0 relations, got {count}"

    # 5. Assert a tradeable EQUIVALENT relation exists
    relations = session.query(LogicalRelation).all()
    assert len(relations) > 0, "No LogicalRelation rows persisted"

    equivalent_tradeable = [
        r for r in relations
        if r.relation_type == RelationType.EQUIVALENT.value
        and r.tradeable_relation is True
    ]
    assert len(equivalent_tradeable) >= 1, (
        f"Expected at least one tradeable EQUIVALENT relation. "
        f"Got relation types: {[r.relation_type for r in relations]}, "
        f"tradeable: {[r.tradeable_relation for r in relations]}"
    )

    # 6. Assert hypothesis_source is tagged correctly
    hypothesis_relation = next(
        (r for r in relations if (r.evidence or {}).get("hypothesis_source") == "hypothesis_generator"),
        None,
    )
    assert hypothesis_relation is not None, (
        "Expected at least one relation tagged as hypothesis_generator source. "
        f"Evidence samples: {[(r.relation_type, r.evidence) for r in relations[:3]]}"
    )

    # 7. Assert semantic analyzer received a typed hypothesis_context (not generic)
    call_kwargs = analyzer.classify.call_args.kwargs
    assert call_kwargs.get("hypothesis_context") is not None, (
        "SemanticRelationAnalyzer.classify should have received a typed hypothesis_context"
    )
    assert "equivalent" in call_kwargs["hypothesis_context"].lower(), (
        f"Expected 'equivalent' in hypothesis_context, got: {call_kwargs['hypothesis_context'][:100]}"
    )


@pytest.mark.anyio
async def test_fixture_same_platform_partition_can_be_tradeable_without_semantic(test_session):
    """
    Sanity check: same-platform markets in the same group can surface a tradeable
    mutually-exclusive / exhaustive-partition proof when the structural signals are strong.
    """
    session = test_session

    pm_a = _raw_market(session, "polymarket", "cand-a", group_id="grp1")
    pm_b = _raw_market(session, "polymarket", "cand-b", group_id="grp1")
    session.flush()

    _compiled_contract(session, pm_a.id)
    _compiled_contract(session, pm_b.id)

    # Same platform, same group — propositions with same family
    prop_a_data = {
        "raw_market_id": pm_a.id,
        "canonical_subject": "election_2025",
        "canonical_predicate": "winner_is",
        "canonical_object": "candidate_a",
        "temporal_deadline": _DL,
        "oracle_focus": "official",
        "oracle_scope": "official",
        "proposition_family": "election:polymarket:wins",
        "partition_hint": True,
        "polarity": "positive",
        "semantic_tags": [],
        "compiler_confidence": 0.9,
    }
    prop_b_data = {
        **prop_a_data,
        "raw_market_id": pm_b.id,
        "canonical_object": "candidate_b",
    }
    session.add(CompiledProposition(
        id=uuid.uuid4(), raw_market_id=pm_a.id, proposition_json=prop_a_data,
        compiler_version="test-v1", compiled_at=_NOW,
    ))
    session.add(CompiledProposition(
        id=uuid.uuid4(), raw_market_id=pm_b.id, proposition_json=prop_b_data,
        compiler_version="test-v1", compiled_at=_NOW,
    ))
    session.flush()

    identity_prov = {
        "canonical_event_id": "event-grp1",
        "identity_status": "verified",
        "identity_confidence": 0.95,
        "identity_version": "identity-v3-runtime",
        "links": {},
    }
    with patch("parallax.prover.service.load_identity_provenance", return_value=identity_prov), \
         patch("parallax.prover.service.load_identity_status") as mock_status, \
         patch("parallax.prover.service.load_identity_confidence", return_value=0.95), \
         patch("parallax.prover.service.load_identity_version", return_value="identity-v3-runtime"), \
         patch("parallax.prover.service.load_identity_blocking_reason", return_value=None):

        from parallax.shared.schemas import IdentityResolutionStatus
        mock_status.return_value = IdentityResolutionStatus.VERIFIED

        graph_repo = PostgresGraphRepository(session)
        service = RelationAnalysisService(session, graph_repo, semantic_analyzer=None)
        await service.run([pm_a, pm_b])

    session.flush()

    # With no semantic analyzer and same-platform same-group markets,
    # the structural and hypothesis paths can still prove partition tradeability.
    relations = session.query(LogicalRelation).all()
    tradeable_count = sum(1 for r in relations if r.tradeable_relation)
    assert tradeable_count >= 1, (
        f"Expected at least 1 tradeable relation for same-platform same-group partition proof, "
        f"got {tradeable_count}. Types: {[r.relation_type for r in relations]}"
    )
    assert any(
        r.relation_type in {RelationType.MUTUALLY_EXCLUSIVE.value, RelationType.EXHAUSTIVE_PARTITION.value}
        for r in relations
    ), f"Expected a partition-style relation. Types: {[r.relation_type for r in relations]}"
